"""relate user to books

Revision ID: c8e300cc1c81
Revises: c7a9c3404b0d
Create Date: 2025-03-18 17:55:57.689929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c8e300cc1c81"
down_revision: Union[str, None] = "c7a9c3404b0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("user_uid", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["user_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "user_uid")
    # ### end Alembic commands ###
